# Профиль dev — запуск БЕЗ Docker и БЕЗ PostgreSQL (встроенная H2 в памяти)
spring:
  datasource:
    url: jdbc:h2:mem:labhau;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: false
  sql:
    init:
      mode: always
      data-locations: classpath:data-dev.sql

logging:
  level:
    org.hibernate.SQL: DEBUG
