# Профиль pg — локальный запуск с PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/labhau_db
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc: DEBUG